### ISSUE TITLE
p2p: version number for messages on the P2P network

### ISSUE THREAD

**Issue by HAOYUatHZ** [rand-chain/rust-randchain#62]
current p2p package contains unnecessary version information. We'd better remove them.

**Comment by SebastianElvis** [comment]
> we should also add ser&deser tests for **currently used version number string**

Relevant tests seem to be put here
https://github.com/rand-chain/rust-randchain/blob/master/message/src/types/version.rs#L41-L61

It seems that it's safe for us to use any value larger than 70001

**Comment by SebastianElvis** [comment]
Detailed protocol specification is captured by issue #66. This issue is no longer needed so closed.
